'''solution of deliquescence and efflorescence RH, generated by eqn_pars.py in fully functioning mode, or by ui_check.py in testing mode'''
# module to estimate deliquescence and efflorescence relative humidity as a function of temperature
<<<<<<< HEAD
# File Created at 2022-01-21 19:36:23.066158
=======
# File Created at 2022-01-23 20:22:43.813300
>>>>>>> b796dafde0c181a7070f1514d48d9f2624db328c

# function for deliquescence
def drh(TEMP):
	
	# inputs: -----------------
	# TEMP - temperature in chamber (K)
	# ---------------------------
	
	# deliquescence relative humidity (fraction 0-1)
	DRH = 0.*TEMP
	return(DRH)

# function for efflorescence
def erh(TEMP):
	
	# inputs: -----------------
	# TEMP - temperature in chamber (K)
	# ---------------------------
	
	# efflorescence relative humidity (fraction 0-1)
	ERH = 0.*TEMP
	return(ERH)
