'''solution of deliquescence and efflorescence RH, generated by eqn_pars.py in fully functioning mode, or by ui_check.py in testing mode'''
# module to estimate deliquescence and efflorescence relative humidity as a function of temperature
<<<<<<< HEAD
# File Created at 2022-02-07 20:23:09.548322
=======
# File Created at 2022-02-08 10:42:38.020683
>>>>>>> 099d1bc1979326bc2b0a25f7992dc56931f28a63

# function for deliquescence
def drh(TEMP):
	
	# inputs: -----------------
	# TEMP - temperature in chamber (K)
	# ---------------------------
	
	# deliquescence relative humidity (fraction 0-1)
	DRH = 0.*TEMP
	return(DRH)

# function for efflorescence
def erh(TEMP):
	
	# inputs: -----------------
	# TEMP - temperature in chamber (K)
	# ---------------------------
	
	# efflorescence relative humidity (fraction 0-1)
	ERH = 0.*TEMP
	return(ERH)
