##########################################################################################
#                                                                                        #
#    Copyright (C) 2018-2024 Simon O'Meara : simon.omeara@manchester.ac.uk               #
#                                                                                        #
#    All Rights Reserved.                                                                #
#    This file is part of PyCHAM                                                         #
#                                                                                        #
#    PyCHAM is free software: you can redistribute it and/or modify it under             #
#    the terms of the GNU General Public License as published by the Free Software       #
#    Foundation, either version 3 of the License, or (at your option) any later          #
#    version.                                                                            #
#                                                                                        #
#    PyCHAM is distributed in the hope that it will be useful, but WITHOUT               #
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS       #
#    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more              #
#    details.                                                                            #
#                                                                                        #
#    You should have received a copy of the GNU General Public License along with        #
#    PyCHAM.  If not, see <http://www.gnu.org/licenses/>.                                #
#                                                                                        #
##########################################################################################
'''solution of ODEs, generated by eqn_pars.py'''
# module to solve system of ordinary differential equations (ODEs) using solve_ivp of Scipy 
# File Created at 2026-07-06 14:19:35.118452

import numpy as np
import scipy.sparse as SP
from scipy.integrate import solve_ivp

# define function
def ode_solv(y, integ_step, rrc,rindx_g, pindx_g, rstoi_g, pstoi_g, nreac_g, nprod_g,
	jac_stoi_g, njac_g, jac_den_indx_g, jac_indx_g, 
	y_arr_g, y_rind_g, uni_y_rind_g, y_pind_g, uni_y_pind_g,
	reac_col_g, prod_col_g, rstoi_flat_g, pstoi_flat_g, rr_arr_g,
	rr_arr_p_g, rowvals, colptrs, comp_num, dil_fac_now, wall_loss,
	jac_flat_rr_idx, jac_flat_stoi, jac_flat_den_indx, jac_flat_data_indx,
	const_comp_indices=None):

	# inputs: -------------------------------------
	# y - initial concentrations (# molecules/cm3)
	# integ_step - the maximum integration time step (s)
	# modelparams.rindx_g - index of reactants per equation
	# modelparams.pindx_g - index of products per equation
	# modelparams.rstoi_g - stoichiometry of reactants
	# modelparams.pstoi_g - stoichiometry of products
	# modelparams.nreac_g - number of reactants per equation
	# modelparams.nprod_g - number of products per equation
	# rrc - reaction rate coefficient
	# modelparams.jac_stoi_g - stoichiometries relevant to Jacobian
	# modelparams.njac_g - number of Jacobian elements affected per equation
	# modelparams.jac_den_indx_g - index of component denominators for Jacobian
	# modelparams.jac_indx_g - index of Jacobian to place elements per equation (rows)
	# Cinfl_now - influx of components with continuous influx 
	#		(# molecules/cm3/s)
	# modelparams.y_arr_g - index for matrix used to arrange concentrations of gas-phase reactants, 
	#	enabling calculation of reaction rate coefficients 
	# modelparams.y_rind_g - index of y relating to reactants for reaction rate 
	# 	coefficient equation
	# modelparams.uni_y_rind_g - unique index of reactants 
	# modelparams.y_pind_g - index of y relating to products
	# modelparams.uni_y_pind_g - unique index of products 
	# modelparams.reac_col_g - column indices for sparse matrix of reaction losses
	# modelparams.prod_col_g - column indices for sparse matrix of production gains
	# modelparams.rstoi_flat_g - 1D array of reactant stoichiometries per equation
	# modelparams.pstoi_flat_g - 1D array of product stoichiometries per equation
	# rr_arr - index for reaction rates to allow reactant loss
	# 	calculation
	# rr_arr_p - index for reaction rates to allow reactant loss
	# 	calculation
	# rowvals - row indices of Jacobian elements
	# colptrs - indices of  rowvals corresponding to each column of the
	# 	Jacobian
	# modelparams.wall_on - flag saying whether to include wall partitioning
	# modelparams.Psat - pure component saturation vapour pressures (# molecules/cm3)
	# act_coeff - activity coefficient of components
	# modelparams.eqn_num - number of gas- and aqueous-phase reactions 
	# modelparams.dil_fac - dilution factor for chamber (fraction of chamber air removed/s)
	# modelparams.RO2_indx - index of organic peroxy radicals
	# modelparams.comp_namelist - chemical scheme names of components
	# modelparams.Psat_Pa - saturation vapour pressure of components (Pa) at starting
	#	temperature of chamber
	# modelparams - reference to program 
	# ---------------------------------------------

	# --- Perf Fix 1: Precompute power mask for rstoi_g ---
	# Most entries are 0.0 (padding) or 1.0 (first-order in each reactant).
	# Only apply ** for the rare entries with rstoi > 1 (e.g. HO2+HO2, NO+NO).
	_pow_mask = (rstoi_g != 1.0) & (rstoi_g != 0.0)
	_pow_stoi = rstoi_g[_pow_mask]
	_has_pow = _pow_mask.any()

	# --- Perf Fix 3: Pre-build Jacobian CSC template ---
	# The sparsity pattern (rowvals, colptrs) never changes; only data changes.
	# Build the sliced [:comp_num, :comp_num] structure once and reuse it.
	_nnz = rowvals.shape[0]
	_test_data = np.arange(_nnz, dtype=np.float64)
	_jac_full = SP.csc_matrix((_test_data, rowvals, colptrs))
	_jac_sliced = _jac_full[:comp_num, :comp_num].tocsc()
	_jac_data_map = _jac_sliced.data.astype(np.intp)
	_jac_template = _jac_sliced.copy()
	_jac_template.data[:] = 0.0

	# --- Perf Fix 2: Cache dict for rr reuse between dydt -> jac ---
	# BDF always calls jac(t, y) right after dydt(t, y) at the same point.
	_rr_cache = {}

	def _compute_rr(y_flat):
		"""Compute reaction rates from flat concentration array (shared by dydt & jac)."""
		rrc_y = np.ones((rindx_g.shape[0] * rindx_g.shape[1]))
		rrc_y[y_arr_g] = y_flat[y_rind_g]
		rrc_y = rrc_y.reshape(rindx_g.shape[0], rindx_g.shape[1], order='C')
		if _has_pow:
			rrc_y[_pow_mask] = rrc_y[_pow_mask] ** _pow_stoi
		return rrc[0:rindx_g.shape[0]] * rrc_y.prod(axis=1)

	def dydt(t, y): # define the ODE(s)
		
		# inputs: ----------------
		# y - concentrations (# molecules/cm3), note when using
		#	scipy integrator solve_ivp, this should have shape
		#	(number of elements, 1)
		# t - time interval to integrate over (s)
		# ---------------------------------------------
		
		# ensure y is correct shape
		if (y.shape[1] > 1):
			y = y[:, 0].reshape(-1, 1)
		# empty array to hold rate of change per component
		# (this is the returned value from dydt)
		dd = np.zeros((y.shape[0], 1))
		
		# gas-phase reactions -------------------------
		# reaction rate (molecules/cm3/s) - Fix 1: optimized power+prod
		rr = _compute_rr(y[:, 0])
		# Fix 2: cache rr for jac reuse
		_rr_cache['t'] = t
		_rr_cache['fp'] = (y[0, 0], y[:, 0].sum())
		_rr_cache['rr'] = rr
		# loss of reactants — np.bincount is ~10x faster than SP.csc_matrix + sum
		dd[:, 0] -= np.bincount(y_rind_g, weights=rr[rr_arr_g]*rstoi_flat_g, minlength=y.shape[0])
		# gain of products
		dd[:, 0] += np.bincount(y_pind_g, weights=rr[rr_arr_p_g]*pstoi_flat_g, minlength=y.shape[0])
		dd[:, 0] -= y[:,0]*dil_fac_now
		dd[:, 0] -= y[:,0]*wall_loss
		# Hold constant species: zero their derivatives so the ODE solver
		# keeps them unchanged throughout the integration step.
		if const_comp_indices is not None:
			dd[const_comp_indices, 0] = 0.0

		dd = dd.flatten()
		return (dd)

	def jac(t, y): # define the Jacobian
		
		# inputs: ----------------
		# y - concentrations (# molecules/cm3), note when using scipy integrator solve_ivp, this should have shape (number of elements, 1)
		# t - time interval to integrate over (s)
		# ---------------------------------------------
		
		# ensure y is correct shape
		if (y.ndim == 2):
			if (y.shape[1] > 1):
				y = y[:, 0].reshape(-1, 1)
		if (y.ndim <= 1):
			y = y.reshape(-1, 1)
		
		# Fix 2: reuse cached rr from dydt when possible
		_fp = (y[0, 0], y[:, 0].sum())
		if _rr_cache.get('t') == t and _rr_cache.get('fp') == _fp:
			rr_j = _rr_cache['rr']
		else:
			rr_j = _compute_rr(y[:, 0])
		
		# vectorised Jacobian
		rr_exp  = rr_j[jac_flat_rr_idx]
		denom   = y[jac_flat_den_indx, 0]
		nonzero = (rr_exp != 0.) & (denom != 0.)
		coeffs  = np.zeros(len(jac_flat_rr_idx), dtype=float)
		coeffs[nonzero] = rr_exp[nonzero] * jac_flat_stoi[nonzero] / denom[nonzero]
		data = np.bincount(jac_flat_data_indx, weights=coeffs, minlength=_nnz).astype(float)
		
		# Fix 3: use pre-built Jacobian template
		j = _jac_template.copy()
		j.data[:] = data[_jac_data_map]

		# Zero Jacobian rows for constant species (consistent with dydt)
		if const_comp_indices is not None:
			for ci in const_comp_indices:
				j[ci, :] = 0.0

		return(j)
	
	# set ODE solver tolerances
	atol = 1e-05
	rtol = 0.0001
	
	# check for underflow issues
	# reaction rate coefficient calculation
	#rrc_y = np.ones((rindx_g.shape[0]*rindx_g.shape[1]))
	#rrc_y[y_arr_g] = y[rindx_g]
	#rrc_y = rrc_y.reshape(rindx_g.shape[0], rindx_g.shape[1], order = 'C')
	# reaction rate coefficient zeroed wherever product of reactant concentrations is zero (including where underflow causes zero, thereby preventing underflows breaking the solver which appears to be an issue on less powerful machines such as HP Spectre Folio) (/s) 
	#rrc[((rrc_y**rstoi_g).prod(axis=1)) == 0.0] = 0.
	
	# call on the ODE solver, note y contains the initial condition(s) (molecules/cm3 (air)) and must be 1D even though y in dydt and jac has shape (number of elements, 1)
	sol = solve_ivp(dydt, [0, integ_step], y, atol = atol, rtol = rtol, method = 'BDF', t_eval = [integ_step], vectorized = True, jac = jac)
	
	if (sol.status == -1): # if integration step failed, then we want to reduce the time step and try again 
		y[0] = -1.e6
	else:
		# force all components in size bins with no particle to zero
		y = np.squeeze(sol.y)
		# return to array
		y = y.flatten()
		
	# return concentration(s) and time(s) following integration
	return(y)
